### ISSUE TITLE
Hello bro, there is no sflow in the mininet directory

### ISSUE THREAD

**Issue by sinsinsinssskrrr** [viettd14/DETECTION-AND-MITIGATION-DDOS-ATTACKS-IN-SDN#1]
![image](https://github.com/viettd14/DETECTION-AND-MITIGATION-DDOS-ATTACKS-IN-SDN/assets/91365848/eb3d9fb1-7405-4902-9da8-09b8340160fd)

**Comment by viettd14** [comment]
Hi, You can download sflow and install according to the link instructions
https://github.com/sflow-rt/mininet-dashboard?tab=readme-ov-file
